### PR TITLE
Remove readline in favour of libedit

### LINKED ISSUE #29: compiled with readline
Readline makes the package output a GPL package. Can we compile this without GPL?

https://github.com/conda-forge/sqlite-feedstock/blob/b4befe4b9b156aa1b30750931f40d3d1f2f8799a/recipe/meta.yaml#L27

This is stated here:

https://www.sqlite.org/cvstrac/wiki?p=ReadLine

### PR DESCRIPTION
**Pull request by hmaarrfk**
readline is gpl, libedit is not.

(I also rerendered, glad to rebase if you want)

Fixes #29

This, or a license change, should be merged in.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I'm not too familiar with libedit but this  looks like a good idea in principle. 

@conda-forge/core what do you think?

**Comment by hmaarrfk** [comment]
If anybody needs it, I'm happy to create a new recipe `sqlite-gpl` for those that need the readline behaviour.

**Comment by hmaarrfk** [comment]
This isn't so much about the pros and con. As it stands, you are linking sqlite with a GPL library, but claiming that the package (distribution) is public domain. It is not, as the binary that is created through it contains GPL'ed code (readline).

So, you should:
1. Either list the package as GPL.
2. Change the dependency.

I will gladly create a "non-gpl" package, but this way, the upgraded version of the sqlite packge doesn't magically change dependencies.

**Comment by hmaarrfk** [comment]
Looking at the results of ldd, it seems that the appropriate solution might be to split this into `libsqlite` and `sqlite`, where `sqlite` is linked to `libreadline`
```
➤ ldd sqlite3                                                                                     (base) 
	linux-vdso.so.1 =>  (0x00007ffcb210b000)
	libncurses.so.6 => /home/mark/miniconda3/bin/./../lib/libncurses.so.6 (0x00007f3d5ad52000)
	libtinfo.so.6 => /home/mark/miniconda3/bin/./../lib/libtinfo.so.6 (0x00007f3d5ab14000)
	libreadline.so.7 => /home/mark/miniconda3/bin/./../lib/libreadline.so.7 (0x00007f3d5a8c0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3d5a5b7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3d5a3b3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3d5a196000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3d59dcc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3d5af7e000)
```

but libsqlite is not

```
ldd libreadline.so                                                                              (base) 
	linux-vdso.so.1 =>  (0x00007fff7feb2000)
	libncurses.so.6 => /home/mark/miniconda3/lib/libncurses.so.6 (0x00007f4b38cc4000)
	libtinfo.so.6 => /home/mark/miniconda3/lib/libtinfo.so.6 (0x00007f4b38a86000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b386bc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b39144000)
```

That said, I am pretty confused as to how to make a split package. Maybe somebody can point me to a full fledge example?

**Comment by hmaarrfk** [comment]
Needless to say, the package that includes executables linked to readline should really be listed as declared a GPL package.

**Comment by bgruening** [comment]
Could you look at how debian is doing this. I usually look up what debian is doing in licensing questions (and others!) https://packages.debian.org/jessie/sqlite3

**Comment by hmaarrfk** [comment]
Does debian list the license of a pacakge somewhere?
It doesn't seem like it in the package.

FWIW, they also split the library and the binary, but I'm not sure that is for licensing reasons. I remember Fedora packages were always split between binary and library for organizational reasons more than licensing reasons.

**Comment by scopatz** [comment]
This is a bad idea, IMO.  libedit is an incomplete clone of readline, and likely to break in weird ways.  [SQLite is meant to be compiled with readline](https://sqlite.org/howtocompile.html), not libedit.  I think that, if anything, there should be an alternative package (`sqlite-nogpl`), or perhaps even a `nogpl-sqlite` so that we could have a nogpl namespace for those who need it.

**Comment by hmaarrfk** [comment]
@scopatz I agree with you that please see PR #31 where I simply split off the package into libsqlite where libsqlite is clearly non-gpl. the command line interface can be GPL, I don't think that will enact the virality of GPL

**Comment by hmaarrfk** [comment]
I'm closing this PR in favour of #31

That said, I think a GPL compatible solution needs to be found soon... this package is linking against a GPL library and claims to be Public Domain.

**Comment by hmaarrfk** [comment]
@jakirkham I see there are 2 problems here:
1. conda-forge are not correctly advertising the license of the combined work. For this package the `/bin/sqlite3` file is a combined work of readline and libsqlite. As such this package is not abiding by GPL.
2. We can split the package in two to avoid GPL issues keeping closer to the library's original license and to stop the virality of the GPL clause.

In this particular case, the GPL combined work is not a library, but an executable. As such, I doubt `readline` will come after you since the virality kinda stops there as you could claim that you were "distributing a work of Public Domain along side GPL work".

That said, I think conda-forge should be careful when they include GPL libraries and claim the combined work is not GPL. 

For this sqlite3, I think the correct approach is to to package the binary as GPL, and the library as libsqlite3. Other packages can then depend on libsqlite3 without being forced to be released under GPL.

This is PR#31, but I fear there is too much 'gardening' to be done with it as it stands.

**Comment by hmaarrfk** [comment]
I definitely think we should piecemeal the package. This makes it clear cut that the `sqlite3` library has value without the GPL code.

Forgetting to include a notice might be forgivable. 
What we definitely want to avoid is the case where the whole `sqlite` package, and the whole `python` package are found to be covered by the GPL. 
If a lawyer finds that the distributions from conda-forge are actually GPL, this might mean that anything that links to `libpython` from conda-forge, becomes GPL (this would be numpy, and then by extention probably most of the conda-forge scientific stack).

Splitting the packages, so that at compile time, only non-gpl code can be pulled in as a library and linked against, is quite important to make the case that `libpython` and `libsqlite` are valuable without readline. That makes the case really clear cut: without readline, you are only mildly inconvenienced.

For python and sqlite, this means isolating two binaries: `/bin/sqlite3` and the readline in `lib-dynload` for python.

At the end of the day, we have to remember that we are never FORCED to include (compile with) `readline` (or any other GPL'ed code). We **choose to**, and that means we must respect the authors' licensing terms.

Conda is great because it is allows us to package cross-OS. The bots, CI's, scripts you all wrote are awesome! Lets ensure we don't greedy and bring it all down.

**Pull request closed without merging**
