### PR TITLE
revise export of win symbols; update to 3.13

### PR DESCRIPTION
**Pull request by msarahan**
Fixes an issue with a missing sqlite3.lib file I had.  Also updates to current sqlite.

### CODE REVIEW

**Comment by msarahan** [comment]
No comments - going to merge this.

**Comment by jakirkham** [comment]
Sorry, totally missed this. Though I'm sure it's fine and am just asking for my clarification. What does this revise of exports do?

**Comment by msarahan** [comment]
Before this PR, we weren't creating the .lib at all.  It must have changed in a recent version of SQlite - the EXPORT bit just was gone from the source code.  This adds something like it back in, so that .lib gets generated, and so that symbols in the DLL are exported appropriately.

**Comment by jakirkham** [comment]
Ah, ok, makes sense. Thanks for explaining.

**Pull request merged**
