### PR TITLE
Install sqlite3ext.h under Win

### PR DESCRIPTION
**Pull request by xylar**
This file already gets installed in unix and is expected in some
downstream packages (libspatialite if nothing else).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by jjhelmus — APPROVED** [review]

**Comment by jjhelmus** [comment]
LGTM, waiting on CI to turn green before merging.

**Comment by xylar** [comment]
@jjhelmus, thanks for the review.  I did a local build just now and it worked, so I think it should be fine.  Let's see.

**Comment by xylar** [comment]
@jjhelmus, thanks again!

**Pull request merged**
